logging:
  level:
    my:
      projects:
        library: TRACE
    root: WARN
mybatis:
  mapperLocations: classpath*:/my/projects/library/db/mappers/*.xml
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 1qazxsw2
    url: jdbc:postgresql://localhost:5432/library
    username: lib_user
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 20000
      minimum-idle: 2
      connection-init-sql: SELECT CURRENT_TIMESTAMP
